version: '3.8'

services:
  db:
    image: cyprientemateu/sixfure-db:${DB_IMAGE_TAG}
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: WEATHER_APP_MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: sixfure
      MYSQL_USER: sixfure
      MYSQL_PASSWORD: WEATHER_APP_MYSQL_PASSWORD
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sixfure
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: cyprientemateu/sixfure-redis:${REDIS_IMAGE_TAG}
    ports:
      - "6379:6379"
    environment:
      REDIS_USER: WEATHER_APP_REDIS_PASSWORD_USERNAME
      REDIS_PASSWORD: WEATHER_APP_REDIS_PASSWORD
    volumes:
      - redis-data:/data
    networks:
      - sixfure
    restart: always

  ui:
    image: cyprientemateu/sixfure-ui:${UI_IMAGE_TAG}
    ports:
      - "3000:3000"
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    networks:
      - sixfure
    restart: always
    depends_on:
      db:
        condition: service_healthy
      auth:
        condition: service_started

  weather:
    image: cyprientemateu/sixfure-weather:${WEATHER_IMAGE_TAG}
    ports:
      - "5000:5000"
    environment:
      APIKEY: WEATHER_API-TOKEN
    networks:
      - sixfure
    restart: always

  auth:
    image: cyprientemateu/sixfure-auth:${AUTH_IMAGE_TAG}
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PASSWORD: WEATHER_APP_MYSQL_ROOT_PASSWORD
    networks:
      - sixfure
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  sixfure:
    driver: bridge

volumes:
  db-data:
  redis-data:
