name: Deploy Sixfure Stack

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, tcc-deploy]

    env:
      DB_IMAGE_TAG: ${{ secrets.DB_IMAGE_TAG }}
      REDIS_IMAGE_TAG: ${{ secrets.REDIS_IMAGE_TAG }}
      UI_IMAGE_TAG: ${{ secrets.UI_IMAGE_TAG }}
      WEATHER_IMAGE_TAG: ${{ secrets.WEATHER_IMAGE_TAG }}
      AUTH_IMAGE_TAG: ${{ secrets.AUTH_IMAGE_TAG }}
      WEATHER_APP_MYSQL_ROOT_PASSWORD: ${{ secrets.WEATHER_APP_MYSQL_ROOT_PASSWORD }}
      WEATHER_APP_MYSQL_PASSWORD: ${{ secrets.WEATHER_APP_MYSQL_PASSWORD }}
      WEATHER_APP_REDIS_PASSWORD: ${{ secrets.WEATHER_APP_REDIS_PASSWORD }}
      WEATHER_APP_REDIS_PASSWORD_USERNAME: ${{ secrets.WEATHER_APP_REDIS_PASSWORD_USERNAME }}
      WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN }}

    steps:
      - name: Create Docker network
        run: docker network create sixfure || true

      - name: Run DB container
        run: |
          docker run -d --name db \
            --network sixfure \
            -e MYSQL_ROOT_PASSWORD=$WEATHER_APP_MYSQL_ROOT_PASSWORD \
            -e MYSQL_DATABASE=sixfure \
            -e MYSQL_USER=sixfure \
            -e MYSQL_PASSWORD=$WEATHER_APP_MYSQL_PASSWORD \
            -v db-data:/var/lib/mysql \
            -p 3306:3306 \
            cyprientemateu/sixfure-db:$DB_IMAGE_TAG

      - name: Run Redis container
        run: |
          docker run -d --name redis \
            --network sixfure \
            -e REDIS_USER=$WEATHER_APP_REDIS_PASSWORD_USERNAME \
            -e REDIS_PASSWORD=$WEATHER_APP_REDIS_PASSWORD \
            -v redis-data:/data \
            -p 6379:6379 \
            cyprientemateu/sixfure-redis:$REDIS_IMAGE_TAG

      - name: Run Weather container
        run: |
          docker run -d --name weather \
            --network sixfure \
            -e APIKEY=$WEATHER_API_TOKEN \
            -p 5000:5000 \
            cyprientemateu/sixfure-weather:$WEATHER_IMAGE_TAG

      - name: Run Auth container
        run: |
          docker run -d --name auth \
            --network sixfure \
            -e DB_HOST=db \
            -e DB_PASSWORD=$WEATHER_APP_MYSQL_ROOT_PASSWORD \
            -p 8080:8080 \
            cyprientemateu/sixfure-auth:$AUTH_IMAGE_TAG

      - name: Run UI container
        run: |
          docker run -d --name ui \
            --network sixfure \
            -e AUTH_HOST=auth \
            -e AUTH_PORT=8080 \
            -e WEATHER_HOST=weather \
            -e WEATHER_PORT=5000 \
            -e REDIS_USER=redis \
            -e REDIS_PASSWORD=redis \
            -p 3000:3000 \
            cyprientemateu/sixfure-ui:$UI_IMAGE_TAG

      - name: Display running containers
        run: docker ps
