name: Check Docker and Git Versions

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  check-versions:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: [tcc-deploy]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Optional: Uncomment to check Docker version
      - name: Check Docker version
        run: docker --version

      - name: Check Git version
        run: git --version
