name: Deploy Weather App to EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, tcc-deploy]

    steps:
      - name: Debug Environment Info
        run: |
          echo "===== GitHub Actions Context ====="
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Actor: $GITHUB_ACTOR"
          echo "Ref: $GITHUB_REF"
          echo "SHA: $GITHUB_SHA"
          echo "Event: $GITHUB_EVENT_NAME"
          echo "Runner Name: $RUNNER_NAME"
          echo "Runner Labels: $RUNNER_LABELS"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "=================================="

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Stop and Remove Existing Containers
        run: |
          echo "Stopping and removing existing containers..."
          sudo docker-compose -f docker-compose.yml down || true

      - name: Pull Latest Images
        run: |
          echo "Pulling latest images for all services..."
          sudo docker pull cyprientemateu/sixfure-db:${{ secrets.DB_IMAGE_TAG }}
          sudo docker pull cyprientemateu/sixfure-redis:${{ secrets.REDIS_IMAGE_TAG }}
          sudo docker pull cyprientemateu/sixfure-ui:${{ secrets.UI_IMAGE_TAG }}
          sudo docker pull cyprientemateu/sixfure-weather:${{ secrets.WEATHER_IMAGE_TAG }}
          sudo docker pull cyprientemateu/sixfure-auth:${{ secrets.AUTH_IMAGE_TAG }}

      - name: Start Containers with Docker Compose
        run: |
          echo "Starting containers with injected secrets..."
          DB_IMAGE_TAG=${{ secrets.DB_IMAGE_TAG }} \
          REDIS_IMAGE_TAG=${{ secrets.REDIS_IMAGE_TAG }} \
          UI_IMAGE_TAG=${{ secrets.UI_IMAGE_TAG }} \
          WEATHER_IMAGE_TAG=${{ secrets.WEATHER_IMAGE_TAG }} \
          AUTH_IMAGE_TAG=${{ secrets.AUTH_IMAGE_TAG }} \
          WEATHER_APP_MYSQL_ROOT_PASSWORD=${{ secrets.WEATHER_APP_MYSQL_ROOT_PASSWORD }} \
          WEATHER_APP_MYSQL_PASSWORD=${{ secrets.WEATHER_APP_MYSQL_PASSWORD }} \
          WEATHER_APP_REDIS_PASSWORD_USERNAME=${{ secrets.WEATHER_APP_REDIS_PASSWORD_USERNAME }} \
          WEATHER_APP_REDIS_PASSWORD=${{ secrets.WEATHER_APP_REDIS_PASSWORD }} \
          WEATHER_API_TOKEN=${{ secrets.WEATHER_API_TOKEN }} \
          sudo -E envsubst < docker-compose.yml | sudo docker-compose -f - up -d

      - name: List Running Containers
        run: |
          echo "Listing running Docker containers:"
          sudo docker ps

      - name: Show Container Logs (Optional - for troubleshooting)
        if: failure()
        run: |
          echo "Showing logs for failed containers..."
          sudo docker ps -a
          sudo docker logs $(sudo docker ps -aq)
